### ISSUE TITLE
thanks so much for this repo

### ISSUE THREAD

**Issue by timelyportfolio** [karlp-asrs/pme-calcs#1]
I didn't know where to thank you, so I thought I would express my appreciation in this issue.  Your slides and code here were extremely helpful to me.  Thanks so much for sharing!

**Comment by abresler** [comment]
Seconded

**Comment by karlpolen** [comment]
just noticed your comment from March 20.  thanks!  glad it was helpful.  we use this code at AZ State Retirement System to underwrite and evaluate all our private market assets.

**Comment by timelyportfolio** [comment]
@karlpolen So glad you saw it, and thanks so much again for open sourcing this!  Guess I will close.
